# Generated by Django 5.0.2 on 2024-02-22 11:04

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=5,
                        max_length=20,
                        prefix="CARD",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("cvv", models.IntegerField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("master", "master"),
                            ("visa", "visa"),
                            ("verve", "verve"),
                        ],
                        default="master",
                        max_length=20,
                    ),
                ),
                ("card_status", models.BooleanField(default=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Transfer", "Transfer"),
                            ("Credit Alert", "Credit Alert"),
                            ("Debit Alert", "Debit Alert"),
                            ("Sent Payment Request", "Sent Payment Request"),
                            ("Recieved Payment Request", "Recieved Payment Request"),
                            ("Funded Credit Card", "Funded Credit Card"),
                            (
                                "Withdrew Credit Card Funds",
                                "Withdrew Credit Card Funds",
                            ),
                            ("Deleted Credit Card", "Deleted Credit Card"),
                            ("Added Credit Card", "Added Credit Card"),
                        ],
                        default="none",
                        max_length=100,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("is_read", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "nid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvxyz",
                        length=10,
                        max_length=25,
                        prefix="",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification",
                "ordering": ["-date"],
            },
        ),
    ]
